### ISSUE TITLE
How to implement a send button to the Server ? 

### ISSUE THREAD

**Issue by ZaidSameer** [Sir-hennihau/Image-Uploader-in-React-Native#2]
I am totally new to RN, Can you please explain How to implement a send button to the Server ?

**Comment by Sir-hennihau** [comment]
Hi, sorry for late response.

The button, placed in render():

`          <TouchableOpacity onPress={this.selectPhotoTapped.bind(this)}>
            <View style={[styles.avatar, styles.avatarContainer, { marginBottom: 20 }]}>
              { this.state.avatarSource === null ? <Text>Select a Photo</Text> :
              <Image style={styles.avatar} source={this.state.avatarSource} />
              }
            </View>
          </TouchableOpacity>`

TouchableOpacity is kind of similar to a button. This one is f.e. for the image. Upload starts in this example script immediatly after picking a photo. If you want, you can seperate the upload from the image picking of course. 


If you want to seperate the code, then add another button/ TO and implement the following parts in it:

1. A form data. 
2. The fetch() function.

Another example, that describes your problem is in one of my other repos: [https://github.com/Sir-hennihau/next/blob/master/app/components/navigator_components/screens/upload_image_screen/UploadImageScreen.js](https://github.com/Sir-hennihau/next/blob/master/app/components/navigator_components/screens/upload_image_screen/UploadImageScreen.js). This does what you are looking for, but i added some more functions like tags etc, that are stored to a database, so don't be confused.


If you need further help, I'd be glad to help you.

**Comment by ZaidSameer** [comment]
This is a great replay, Many thanks to you, I really appreciate your kind
help.

Greetings from Iraq :)
